
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.*;
import weka.core.Instances;
import weka.classifiers.*;
import weka.classifiers.functions.MultilayerPerceptron;
import weka.classifiers.bayes.NaiveBayes;
import weka.classifiers.lazy.IBk;
import weka.classifiers.trees.J48;




public class PoliceAcademyFrame2 extends javax.swing.JFrame {

    /** Creates new form PoliceAcademyFrame */
    public PoliceAcademyFrame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Output_Text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Police Cadet Evaluation");

        jLabel1.setText("1. Select Classifier, 2 Press Train, 3 Edit attributes, 4 Press Evaluate.");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Age – the age at which the cadet started studying to become a police officer");

        jTextField1.setText("25");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("AvG – average grade at the time of graduation (scale 1-10)");

        jTextField2.setText("7.2");

        jLabel4.setText("Chdn – number of children at the time of graduation");

        jTextField3.setText("1");

        jLabel5.setText("ExEd– Extra university-level or equivalent education (years)");

        jTextField4.setText("2");

        jLabel6.setText("CR – criminal record (0=No, 1=Yes)");

        jTextField5.setText("1");

        jLabel7.setText("Sex – sex of the cadet (0 = Male, 1 = Female)");

        jTextField6.setText("1");

        jLabel8.setText("SecE – Other experience in the security sector (0 = No, 1 = Yes)");

        jTextField7.setText("0");

        jLabel9.setText("AvgE – The average of five years. Scale 1-5");

        jTextField8.setText("2.6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addComponent(jLabel3)
            .addComponent(jLabel4)
            .addComponent(jLabel5)
            .addComponent(jLabel6)
            .addComponent(jLabel7)
            .addComponent(jLabel8)
            .addComponent(jLabel9)
            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Train");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Naive Bayes", "KNN", "C4.5", "Neural Networks" }));

        jButton2.setBackground(new java.awt.Color(255, 204, 153));
        jButton2.setText("Evaluate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 153));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Output_Text.setFont(new java.awt.Font("Tahoma", 1, 24));
        Output_Text.setText("        ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel10.setText("InterMediate Window:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Output_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(270, 270, 270))
                            .addComponent(jScrollPane1))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Output_Text, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Instances train = new Instances(new FileReader("police.arff"));
            train.setClassIndex(train.numAttributes()-1);
                   
            if (jComboBox1.getSelectedItem() == "Neural Networks")
            {
                
                try {
                    mp.buildClassifier(train);
                   
                } catch (Exception ex) {
                    Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(mp.toString());
                jTextArea1.setText(mp.toString());
            }
            if (jComboBox1.getSelectedItem() == "Naive Bayes")
            {
               
                try {
                    nb.buildClassifier(train);
                } catch (Exception ex) {
                    Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(nb.toString());
                jTextArea1.setText(nb.toString());
            }

            if (jComboBox1.getSelectedItem() == "KNN")
            {
                
                try {
                    knn.buildClassifier(train);
                } catch (Exception ex) {
                    Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(knn.toString());
                 jTextArea1.setText(knn.toString());
            }

            if (jComboBox1.getSelectedItem() == "C4.5")
            {
                
                try {
                    c45.buildClassifier(train);
                } catch (Exception ex) {
                    Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(c45.toString());
                 jTextArea1.setText(c45.toString());
            }
        } catch (IOException ex) {
            Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            FileWriter out = null;
            String att1 = jTextField1.getText();
            String att2 = jTextField2.getText();
            String att3 = jTextField3.getText();
            String att4 = jTextField4.getText();
            String att5 = jTextField5.getText();
            String att6 = jTextField6.getText();
            String att7 = jTextField7.getText();
            String att8 = jTextField8.getText();
            String text = "@relation police.txt\n\n" + "@attribute Age numeric\n" + "@attribute AvgG numeric\n" + "@attribute Chdn numeric\n" + "@attribute ExEd numeric\n" + "@attribute CR numeric\n" + "@attribute Sex numeric\n" + "@attribute SecE numeric\n" + "@attribute AvgE numeric\n" + "@attribute FinalE {Pass,Fail}\n" + "@data\n";
            text += att1 + "," + att2 + "," + att3 +","+ att4 + "," + att5 + "," + att6 + "," + att7 + "," + att8 + ",Pass\n";
            File outputFile = new File("test.arff");
            out = new FileWriter(outputFile);
            out.write(text);
            out.close();
            //load the test instance....
            Instances test = new Instances(new FileReader("test.arff"));
            test.setClassIndex (test.numAttributes()-1);
            //evaluate the test using the selected algorithm
            Evaluation eval = null;
            try {
                eval = new Evaluation(test);
            } catch (Exception ex) {
                Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
            }

             if (jComboBox1.getSelectedItem() == "Neural Networks")
             {
                try {
                    eval.evaluateModel(mp, test);
                    jTextArea1.setText(eval.toSummaryString());
                    double clsLabel = mp.classifyInstance(test.instance(0));
                    if (clsLabel==0)
                    {
                        Output_Text.setBackground(Color.green);
                        Output_Text.setText("PASS");
                    }
                    else
                         {
                        Output_Text.setBackground(Color.red);
                        Output_Text.setText("FAIL");
                          }
                } catch (Exception ex) {
                    Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
             }
             if (jComboBox1.getSelectedItem() == "Naive Bayes")
                 {
                try {
                    eval.evaluateModel(nb, test);
                    jTextArea1.setText(eval.toSummaryString());
                    double clsLabel = nb.classifyInstance(test.instance(0));
                    if (clsLabel==0)
                    {
                        Output_Text.setBackground(Color.green);
                        Output_Text.setText("PASS");
                    }
                    else
                         {
                        Output_Text.setBackground(Color.red);
                        Output_Text.setText("FAIL");
                          }


                } catch (Exception ex) {
                    Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
             }
             if (jComboBox1.getSelectedItem() == "KNN")
             {
                try {
                    eval.evaluateModel(knn, test);
                    jTextArea1.setText(eval.toSummaryString());
                    double clsLabel = knn.classifyInstance(test.instance(0));
                    if (clsLabel==0)
                    {
                        Output_Text.setBackground(Color.green);
                        Output_Text.setText("PASS");
                    }
                    else
                         {
                        Output_Text.setBackground(Color.red);
                        Output_Text.setText("FAIL");
                          }
                } catch (Exception ex) {
                    Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
             }
             if (jComboBox1.getSelectedItem() == "C4.5")
             {
                try {
                    eval.evaluateModel(c45, test);
                    jTextArea1.setText(eval.toSummaryString());
                    double clsLabel = c45.classifyInstance(test.instance(0));
                    if (clsLabel==0)
                    {
                        Output_Text.setBackground(Color.green);
                        Output_Text.setText("PASS");
                    }
                    else
                         {
                        Output_Text.setBackground(Color.red);
                        Output_Text.setText("FAIL");
                          }
                } catch (Exception ex) {
                    Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
             }

        } catch (IOException ex) {
            Logger.getLogger(PoliceAcademyFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }




    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Output_Text.setBackground(Color.white);
        Output_Text.setText("");
        jTextArea1.setText("");
        jTextField1.setText("25");
        jTextField2.setText("7.2");
        jTextField3.setText("1");
        jTextField4.setText("2");
        jTextField5.setText("1");
        jTextField6.setText("1");
        jTextField7.setText("0");
        jTextField8.setText("2.5");

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceAcademyFrame2().setVisible(true);

            }
        });
    }
MultilayerPerceptron mp = new MultilayerPerceptron();
NaiveBayes nb = new NaiveBayes();
IBk knn = new IBk();
J48 c45 = new J48();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Output_Text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
